services:
  nextjs:
    ports:
      - 3000:3000
    build:
      context: .
      dockerfile: Dockerfile
    command: npm run dev
    volumes:
      - .:/app
  json-server:
    ports:
      - 3001:3001
    build:
      context: .
      dockerfile: Dockerfile
    command: npm run mock
    volumes:
      - .:/app